[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
repository = "https://github.com/ryanisaacg/quicksilver"

[dependencies]
gl = "0.7"
glutin = "0.11"
image = "0.18"
rand = "0.3"
rodio = "0.5"
tiled = "0.7"
