[package]
name = "quicksilver"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
build = "build.rs"

[lib]
name = "qs"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/bin.rs"

[dependencies]
gl = "0.6.0"
imagefmt = "4.0.0"
sdl2 = "0.30.0"
