[package]
name = "quicksilver"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]

[lib]
name = "qs"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/bin.rs"

[dependencies]
gl = "*"
imagefmt = "*"
glutin = "*"
