[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
repository = "https://github.com/ryanisaacg/quicksilver"
license = "MIT/Apache-2.0"

[dependencies]
gl = "0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.11"
image = "0.18"
rand = "0.4.1"
rodio = "0.5"

