[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.1.0"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
repository = "https://github.com/ryanisaacg/quicksilver"

[dependencies]
gl = "~0.6"
glutin = "~0.10"
image = "~0.17"
tiled = "~0.7"
